version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose port 8000 of the container to port 8000 of the host
    env_file:
      - ./server/.env # Reference the .env file for backend variables

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Expose port 80 of the container to port 3000 of the host
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/ # Frontend environment variable
